"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tablineAbi = void 0;
// AUTO-GENERATED by scripts/gen-abi.mjs from forge output. Do not edit.
exports.tablineAbi = [
    {
        "type": "function",
        "name": "MIN_PERIOD",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint32",
                "internalType": "uint32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "cancel",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "createPlan",
        "inputs": [
            {
                "name": "token",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "payout",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "keeper",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "amount",
                "type": "uint96",
                "internalType": "uint96"
            },
            {
                "name": "period",
                "type": "uint32",
                "internalType": "uint32"
            },
            {
                "name": "kind",
                "type": "uint8",
                "internalType": "enum Tabline.PlanKind"
            }
        ],
        "outputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "isDue",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "planCount",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "plans",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "merchant",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "keeper",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "payout",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "token",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "amount",
                "type": "uint96",
                "internalType": "uint96"
            },
            {
                "name": "period",
                "type": "uint32",
                "internalType": "uint32"
            },
            {
                "name": "kind",
                "type": "uint8",
                "internalType": "enum Tabline.PlanKind"
            },
            {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "resume",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setActive",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setKeeper",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "keeper",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setPayout",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "payout",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "settle",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "chargeKey",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "settled",
        "inputs": [
            {
                "name": "id",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "snapshot",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "subscriptions",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "startedAt",
                "type": "uint48",
                "internalType": "uint48"
            },
            {
                "name": "nextDueAt",
                "type": "uint48",
                "internalType": "uint48"
            },
            {
                "name": "cancelled",
                "type": "bool",
                "internalType": "bool"
            },
            {
                "name": "totalPaid",
                "type": "uint128",
                "internalType": "uint128"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "event",
        "name": "Cancelled",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Charged",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "chargeKey",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "nextDueAt",
                "type": "uint48",
                "indexed": false,
                "internalType": "uint48"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "KeeperChanged",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "keeper",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "PayoutChanged",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "payout",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "PlanActiveChanged",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "active",
                "type": "bool",
                "indexed": false,
                "internalType": "bool"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "PlanCreated",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "merchant",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "token",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            },
            {
                "name": "payout",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            },
            {
                "name": "keeper",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            },
            {
                "name": "amount",
                "type": "uint96",
                "indexed": false,
                "internalType": "uint96"
            },
            {
                "name": "period",
                "type": "uint32",
                "indexed": false,
                "internalType": "uint32"
            },
            {
                "name": "kind",
                "type": "uint8",
                "indexed": false,
                "internalType": "enum Tabline.PlanKind"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Resumed",
        "inputs": [
            {
                "name": "planId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "subscriber",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AlreadySettled",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidParams",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NoSnapshot",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotDue",
        "inputs": [
            {
                "name": "nextDueAt",
                "type": "uint48",
                "internalType": "uint48"
            }
        ]
    },
    {
        "type": "error",
        "name": "NotMerchant",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotOperator",
        "inputs": []
    },
    {
        "type": "error",
        "name": "PaymentNotReceived",
        "inputs": []
    },
    {
        "type": "error",
        "name": "PlanInactive",
        "inputs": []
    },
    {
        "type": "error",
        "name": "SubscriptionCancelled",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UnknownPlan",
        "inputs": []
    },
    {
        "type": "error",
        "name": "WrongAmount",
        "inputs": []
    }
];
