// Regenerates src/abi.ts and test/helpers/bytecode.ts from forge artifacts. Run `forge build` first.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../../out/", import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), "utf8"));
const tabline = read("Tabline.sol/Tabline.json");
const usdc = read("MockUSDC.sol/MockUSDC.json");
writeFileSync(
  new URL("../src/abi.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/gen-abi.mjs from forge output. Do not edit.\nexport const tablineAbi = ${JSON.stringify(tabline.abi, null, 2)} as const;\n`,
);
writeFileSync(
  new URL("../test/helpers/bytecode.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/gen-abi.mjs. Test-only.\nexport const tablineBytecode = "${tabline.bytecode.object}" as const;\nexport const mockUsdcBytecode = "${usdc.bytecode.object}" as const;\nexport const mockUsdcAbi = ${JSON.stringify(usdc.abi)} as const;\n`,
);
console.log("abi + bytecode written");
